/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicio;

import java.util.Scanner;

public class App {
    
    //Escreva um algoritmo que leia dois valores inteiro distintos e informe qual é o maior;

    public static void main(String[] args) {
        
        Scanner scanner = new Scanner(System.in);

        System.out.println("Digite o primeiro número inteiro");
        int numero1 = scanner.nextInt();

        System.out.println("Digite o segundo número inteiro");
        int numero2 = scanner.nextInt();

        scanner.close();

        if (numero1 > numero2) {
            System.out.println("O maior número é: " + numero1);
        } else if (numero2 > numero1) {
            System.out.println("O maior número é: " + numero2);
        } else {
            System.out.println("Os números são iguais");
        }
    }
}
