/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicio;

import java.util.Scanner;

public class App {

    /*Leia uma temperatura em graus Celsius e apresentá-la convertida em graus Fahrenheit. A fórmula de 
    conversão é: F=(9*C+160) / 5, sendo F a temperatura em Fahrenheit e C a temperatura em Celsius; */
   

    public static void main(String[] args) {
        
        Scanner scanner = new Scanner(System.in);

        System.out.print("Digite a temperatura em Celsius: ");
        double temperaturaCelsius = scanner.nextDouble();

        scanner.close();

        double temperaturaFahernheit = (9 * temperaturaCelsius + 160) /5;

        System.out.println("A temperatura em Celsius é : " + temperaturaCelsius + "°C" + " convertido para Fahrenheit é : " + temperaturaFahernheit + "°F");
    }
}
