/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicio;

import java.util.Scanner;

public class App {
   
    

    public static void main(String[] args) {
        
       Scanner scanner = new Scanner(System.in);
       
       System.out.println("Digite o nome do vendedor");
       String nomeVendedor = scanner.nextLine();
       
       System.out.println("Digite o salário fixo do vendedor");
       double salarioFixo = scanner.nextDouble();

       System.out.println("Digite o total de vendas efetuadas no mês");
       double totalVendas = scanner.nextDouble();

       scanner.close();

       double comissao = 0.15 * totalVendas;

       double salarioTotal = salarioFixo + comissao;

       System.out.println("Nome do vendedor" + nomeVendedor);
       System.out.println("Salário Fixo" + salarioFixo);
       System.out.println("Comissão (15% das vendas): R$" + comissao);
       System.out.println("Salário total no final do mês: R$" + salarioTotal);


    }
}
