/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicio;

import java.util.Scanner;

public class App {
    
    /*O custo de um carro novo ao consumidoré a soma do custo de fábrica mais o percentual do distribuidor e 
    dos impostos aplicados (primeiro os impostos são aplicados sobre o custo de fábrica, e depois o percentual 
    do distribuidor sobre o resultado). Supondo que o percentual do distribuidor seja de 28% e os impostos 
    45%, escreva um algoritmo que leia o custo de fábrica de um carro e informe o custo ao consumidor do 
    mesmo */

    public static void main(String[] args) {
        
        Scanner scanner = new Scanner(System.in);

        System.out.println("Digite o custo de fábrica do carro: R$ ");
        double custoFabrica = scanner.nextDouble();

        scanner.close();

        double percentualDistribuidor = 0.28; //28%
        double taxaImpostos = 0.45; // 45%

        double custoConsumidor = custoFabrica + (custoFabrica* taxaImpostos) + (custoFabrica * percentualDistribuidor);


        System.out.println("O custo ao consumidor do carro é:  R$ " + custoConsumidor);

    }
}
