/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicio;

import java.util.Scanner;

public class App {
    

    public static void main(String[] args) {
        
        Scanner scanner = new Scanner(System.in);

        int totalCarrosAte2000 = 0;
        int totalGeral = 0;

        while (true) {
            System.out.println("Digite o ano do veículo (0 para sair): ");
            int anoVeiculo = scanner.nextInt();

            if (anoVeiculo == 0) {
                break;
            }

            System.out.println("Digite o valor do veículo: R$ ");
            double valorVeiculo = scanner.nextDouble();

            double desconto;

            if (anoVeiculo <= 2000) {
                desconto = valorVeiculo * 0.12; //12 de desconto
                totalCarrosAte2000++;
            } else {
                desconto = valorVeiculo * 0.07; //7% de desconto
            }
            double valorAPagar = valorVeiculo - desconto;
            totalGeral++;

            System.out.println("Valor de desconto: R$ " + desconto);
            System.out.println("Valor a ser pago pelo cliente: R$ " + valorAPagar);
            
        }

        System.out.println("Total de carros até 2000: " + totalCarrosAte2000);
        System.out.println("Total geral de carros: " + totalGeral);

        scanner.close();

    }
}
