/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicio;

import java.util.Scanner;

public class App {
    
    /*Faça um algoritmo que receba um valor que foi depositado e exiba o valor com rendimento após um 
      mês.Considere fixo o juro da poupança em 0,07% a. m; */

    public static void main(String[] args) {
        
        Scanner scanner = new Scanner(System.in);

        System.out.println("Digite o valor depositado: R$ ");
        double valorDepositado = scanner.nextDouble();

        scanner.close();


        double taxaDeJurosMensal = 0.0007;

        double valorComRendimento = valorDepositado + (valorDepositado * taxaDeJurosMensal);

        System.out.println("O valor com rendimento após um mês é: R$ " + valorComRendimento);
    }
}
