/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicio;

import java.util.Scanner;

public class App {

    /*Elabore um algoritmo que efetue a apresentação do valor da conversão em real (R$) de um valor lido em 
    dólar (US$). O algoritmo deverá solicitar o valor da cotação do dólar e também a quantidade de dólares 
    disponíveis com o usuário */
    

    public static void main(String[] args) {
        
        Scanner scanner = new Scanner(System.in);

        System.out.println("Digite a cotação do dólar (valor do dolar em reais): ");
        double cotacaoDolar = scanner.nextDouble();

        System.out.println("Digite a quantidade de dólares disponíveis: ");
        double quantidadeDolares = scanner.nextDouble();

        scanner.close();

        double valorEmReais = cotacaoDolar * quantidadeDolares;

        System.out.println("O valor em reais é: R$ " + valorEmReais);

    }
}
