/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicio;

import java.util.Scanner;

public class App {
    
    /*Faça um algoritmo que receba o preço de custo de um produto e mostre o valor de venda. Sabe-se que o 
      preço de custo receberá um acréscimo de acordo com um percentual informado pelo usuário */

    public static void main(String[] args) {
        
        Scanner scanner = new Scanner(System.in);

        System.out.println("Digite o preço de custo do produto: R$ ");
        double precoCusto = scanner.nextDouble();
        
        System.out.println("Digite o percentual de acréscimo (em %): ");
        double percentualAcrescimo = scanner.nextDouble();

        scanner.close();

        double valorVenda = precoCusto * (1 + (percentualAcrescimo / 100));

        System.out.println("O valor de venda do produto é: R$ " + valorVenda);

    }
}
