/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicio;

import java.util.Scanner;

public class App {

    /*Escreva um algoritmo para determinar o consumo médio de um automóvel sendo fornecida a distância 
      total percorrida pelo automóvel e o total de combustível gasto */

    public static void main(String[] args) {
       
        Scanner scanner = new Scanner(System.in);

        System.out.println("Digite a distância total percorrida (em quilômetros)");
        float distanciaPercorrida = scanner.nextFloat();

        System.out.println("Digite o total combustível gasto (em litros)");
        float combustivelGasto = scanner.nextFloat();

        scanner.close();

        float consumoMedio = distanciaPercorrida / combustivelGasto;

        System.out.println("O consumo médio do automóvel é de " + consumoMedio + " km/L.");


    }
}
