/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicio;

import java.util.Scanner;

public class App {
    

    public static void main(String[] args) {
        
        Scanner scanner = new Scanner(System.in);

        int contador = 0;

        for (int i = 1; i <= 80; i++) {
            System.out.println("Digite o número " + i + ": ");
            int numero = scanner.nextInt();

            if (numero >= 10 && numero <= 150) {
                contador++;
            }
        }

        scanner.close();

        System.out.println("Quantidade de números no intervalo entre 10 e 150: " + contador);
    }
}
