/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicio;

import java.util.Scanner;

/*Leia dois valores para as variáveis A e B, e efetuar as trocas dos valores de forma que a variável A passe a 
  possuir o  valor da variável B e a variável B passe a possuir o valor da variável A. Apresentar os valores 
  trocados */

public class App {
   

    public static void main(String[] args) {
        
        Scanner scanner = new Scanner(System.in);

        System.out.println("Digite o valor de A:");
        int A = scanner.nextInt();

        System.out.println("Digite o valo de B:");
        int B = scanner.nextInt();

        int temp = A;
        A = B;
        B = temp;

        System.out.println("Valores trocados: ");
        System.out.println("A = " + A);
        System.out.println("B = " + B);

        scanner.close();

    }
}
